Fixing build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -11,6 +11,15 @@ jobs:
 
     steps:
 
+    - name: Check secret exists
+      run: |
+          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
+          echo "Secret missing"
+          exit 1
+          else
+            echo "Secret exists"
+          fi 
+
     - name: Checkout repo
       uses: actions/checkout@v4
 
